name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Full Stack Application
      run: docker build . --file Dockerfile --tag internet-stability-tracker:$(date +%s)
    
    - name: Build Backend Service
      run: docker build ./backend --file backend/Dockerfile --tag ist-backend:$(date +%s)
    
    - name: Build Frontend Service
      run: docker build ./frontend --file frontend/Dockerfile --tag ist-frontend:$(date +%s)
